name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install nix
      uses: cachix/install-nix-action@v5
    - name: install cachix
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install
    - name: enable cachix for emacs-ci
      run: cachix use emacs-ci
    - name: check if nix is installed
      run: nix-env --version
    - uses: actions/checkout@v1
    # TODO: Delete after successfully running Emacs on GitHub Actions
    - name: Install Emacs
      run: nix-env -iA emacs-25-2 -f https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz
    - run: emacs --version
    - name: Run tests
      run: |
        nix-build -A byte-compile --no-out-link --quiet
        nix-build -A checkdoc --no-out-link --quiet
        nix-shell -A package-lint --pure --quiet
